name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Workflow test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Maven Package
        run: mvn -B clean package --file ./pom.xml -DskipTests
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: make test-coverage
          run: make test-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Save report
      run: |
          coverage html
      - name: Check coverage
      run: |
          coverage report --fail-under=80
